mesh-1478: publish to pypi

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -137,14 +137,14 @@ jobs:
           thresholdAll: 0.54
 
       - name: setup java
-        if: github.actor!= 'dependabot[bot]' && (success() || failure())
+        if: github.actor != 'dependabot[bot]' && (success() || failure())
         uses: actions/setup-java@v3
         with:
           distribution: "corretto"
           java-version: "17"
 
       - name: provision sonar-scanner
-        if: github.actor!= 'dependabot[bot]' && (success() || failure())
+        if: github.actor != 'dependabot[bot]' && (success() || failure())
         run: |
           export SONAR_VERSION="4.7.0.2747"
           wget -q "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}.zip" -O sonar-scanner.zip
@@ -153,7 +153,7 @@ jobs:
           scripts/sonar_tests.py
 
       # - name: run sonar scan
-      #   if: github.actor!= 'dependabot[bot]' && (success() || failure())
+      #   if: github.actor != 'dependabot[bot]' && (success() || failure())
       #   run: |
       #     PATH="$PWD/sonar-scanner/bin:$PATH"
       #     if [[ "${{ github.event_name }}" == "pull_request" ]]; then
@@ -168,7 +168,7 @@ jobs:
 
 
       - name: archive reports
-        if: github.actor!= 'dependabot[bot]' && (success() || failure())
+        if: github.actor != 'dependabot[bot]' && (success() || failure())
         uses: actions/upload-artifact@v3
         with:
           name: reports
@@ -263,3 +263,63 @@ jobs:
           echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
           echo "${version}"
 
+
+  publish:
+    runs-on: ubuntu-latest
+    if: github.repository == 'NHSDigital/nhs-aws-helpers' && github.actor != 'dependabot[bot]'
+    needs:
+      - coverage
+      - lint
+      - tox
+    steps:
+      - name: checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: print branch info
+        run: |
+          git branch
+          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
+          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
+          git log --oneline -n 10
+
+      - name: clean
+        run: |
+          git clean -fdx
+          find . -type f | xargs chmod g+w
+
+      - name: merge into base_branch
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          echo base branch "${{ github.base_ref }}"
+          echo pr branch "${{ github.head_ref }}"
+          git checkout "${{ github.base_ref }}"
+          git checkout -b "merging-${{ github.event.number }}"
+          git merge --ff-only "${{ github.event.pull_request.head.sha }}"
+
+      - name: setup python
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.8"
+
+      - name: setup poetry
+        uses: abatilo/actions-poetry@v2
+        with:
+          poetry-version: 1.5.1
+
+      - name: add poetry plugins
+        run: |
+          poetry self add "poetry-dynamic-versioning[plugin]"
+
+      - name: poetry build
+        run: |
+          poetry build --format=wheel
+
+      - name: poetry config
+        run: |
+          poetry config repositories.testpypi https://test.pypi.org/legacy/
+          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}
+
+      - name: poetry test publish
+        run: poetry publish -r testpypi
